---
title: "old introduction notes"
output: html_document
---


Prediction models are a useful tool in clinical medicine [@ewout_intro]. Often, the purpose of a clinical prediction model is to estimate a patient's risk of experiencing a particular health event (e.g., disease). Risk estimates can be used to inform clinical decisions; for instance, to decide if a patient is a good candidate for surgery [@annals; @achilles]. Due to the rare nature of many diseases, data available to train clinical prediction models often exhibit class imbalance (i.e., observations from patients with vs. without the event of interest are not equally represented in the data).  When prediction models are trained using imbalanced data, model performance is diminished; performance for the underrepresented class suffers the most [@cip; @lp2]. Consequently, class imbalance correction methodologies are proposed as a solution [@cip; @summary_m; @lp; @summary_h].\
\
There is no scarcity of imbalance corrections proposed to solve the "class imbalance problem", summarized here [@summary_m; @lp; @summary_h].  Similarly, there is also no scarcity of metrics which may be used to measure their effectiveness [@ref1; @ref2; @ref3]. Interestingly, the benefits of imbalance correction methodologies are presented using a set of a performance criteria which are insufficient for assessing model performance in a clinical context.  In particular, information regarding the effect of imbalance corrections on model calibration is sparse.\
\
Why is model calibration an important metric to consider? When a prediction model is developed for clinical use, each patients personal predicted risk is the entity that is used to inform clinical decisions. Consequently, the reliability of personal predicted risks is quite a relevant metric of model performance.  We determine the reliability of personal predicted risks by measuring prediction model calibration. Model calibration is a measure of how much agreement there is between the predicted risks and the observed event fractions [@achilles]. For instance, if 100 people are given a risk prediction of 20%, this should correspond to 20/100 of these people actually experiencing the event.  If a model is poorly calibrated, it may produce risk estimates that are misleading [@achilles]. A poorly calibrated model may produce predicted risks that consistently over- or under-estimate true risk or that are too extreme (too close to 0 or 1) or too modest [@achilles]. This can lead to poor treatment decisions or to clinicians communicating false reassurance or hope to patients [@achilles ; 12days]. For this reason, it is considered insufficient to assess a clinical prediction model without considering model calibration [@epi].\
\
Only one study has assessed the impact of imbalance corrections on model calibration [@ruben]. In this study, the authors demonstrate that class imbalance corrections do more harm than good; implementing imbalance corrections resulted in dramatically deteriorated model calibration, to the point that no corrections were recommended [@ruben]. In this study, prediction models were developed using logistic regression or
penalized logistic regression [@ruben]. In practice, most prediction models developed for clinical use do not use regression based methods [@constanza]. Rather, a recent systematic review of clinical prediction models indicated that other classification algorithms, like support vector machine and tree-based methods, are more common [@constanza]. The impact of imbalance corrections on model calibration is currently unknown for prediction models developed using these other classification algorithms.\
\
Motivated by the work of Goorbergh and colleagues [@ruben], we must ensure that the "cure" is not worse than the disease. In our research, we assess the impact of imbalance corrections on model calibration for prediction models trained with a wide variety of classification algorithms including: logistic regression, support vector machine, random forest, XGBoost RUSBoost and EasyEnsemble. Using Monte Carlo simulations, we answer the question: Can implementing class imbalance corrections improve the out-of-sample predictive performance of clinical prediction models without compromising model calibration? 