---
title: "Untitled"
author: "Week 1"
date: "2023-03-22"
output: html_document
---

```{r, warning = F, message = F}
library(tidyverse)
library(ggridges)
library(patchwork)

source("process_results.R")
```

```{r}
check_if_same <- function(df1, df2){
  pair_id = c(1:30)
  check   = c()
  
  for (i in pair_id){
    a <- df1 %>% filter(pair_id == i)
    b <- df2 %>% filter(pair_id == i)
    
    check[i] <- identical(a,b)
  }
  return(check)
}
```

```{r}
A<- get_summary("testing/testA")
```

```{r}
A$overall_dataframe %>% 
  filter(pair_id == 1)
```

```{r}
B <- get_summary("testing/testB")
```

```{r}
B$overall_dataframe%>% 
  filter(pair_id == 29)
```

```{r}
C <- get_summary("testing/testC")
C$overall_dataframe %>% 
  filter(pair_id == 1)
```

```{r}
# compare with A and B 

same <- check_if_same(A$overall_dataframe, B$overall_dataframe)
which(same)
```

```{r}
# compare B and C

same <- check_if_same(B$overall_dataframe, C$overall_dataframe)
which(same)
```
```{r}
# compare A and C

same <- check_if_same(A$overall_dataframe, C$overall_dataframe)
which(same)
```
# final test 

```{r}
D <- get_summary("testing/testD")$overall_dataframe

sameA <- check_if_same(D, A$overall_dataframe)
sameB <- check_if_same(D, B$overall_dataframe)
sameC <- check_if_same(D, C$overall_dataframe)
which(sameA)
which(sameB)
which(sameC)
```

# results from full simulation 
```{r}
sc2 <- get_summary("sc2")

sc2 <- 
  sc2$overall_dataframe %>%   
  mutate(iter = as.numeric(iter)) %>% 
  filter(iter > 413 & iter < 429) %>% 
  mutate(iter = as.character(iter), 
         int  = as.character(int), 
         slp  = as.character(slp))

# check with A

sameA <- check_if_same(sc2, A$overall_dataframe)
sameB <- check_if_same(sc2, B$overall_dataframe)
sameC <- check_if_same(sc2, C$overall_dataframe)
sameD <- check_if_same(sc2, D)
which(sameA)
which(sameB)
which(sameC)
which(sameD)
```



