---
title: "???"
author: "Week 1"
date: "2023-03-10"
output: pdf_document
---

```{r}
a <- list.files(path = "./sim_results/sc/", pattern = ".rds") %>%
  paste0("./Data/sim/", .) %>% 
  map(readRDS) %>% 
  bind_rows()
```

```{r}

sc = 3
pair_id = 6
start = 1
stop = 100

p6 <- readRDS(paste0("sim_results/predictions/sc", sc, "_p", pair_id, "_", start, "_", stop,".rds"))
r6 <- readRDS(paste0("sim_results/per_iter_results/sc", sc, "_p", pair_id, "_", start, "_", stop,".rds"))
```


```{r}
r1
r2
r3
r4
r5
```
```{r}
p5
```


```{r}
calibration_plot(p5)
```

```{r}
sum(p5$problematic)
```


```{r}
n <- sample(100, 10)

p5 %>% 
  mutate(iter = as.factor(iter)) %>% 
  filter(iter %in% n) %>% 
  ggplot(aes(x = pred, y = iter)) + 
  geom_density_ridges(fill = "aliceblue", scale = 0.5)+
  theme_minimal()

p4 %>% 
  mutate(iter = as.factor(iter)) %>% 
  filter(iter %in% n) %>% 
  ggplot(aes(x = pred, y = iter)) + 
  geom_density_ridges(fill = "aliceblue", scale = 0.5)+
  theme_minimal()
```
```{r}
sum(p5$pred <0)
```
```{r}
ok <- p5 %>% 
  filter (pred < 0) %>% 
  dplyr::select(pred) %>%
  ggplot() + 
    geom_density(aes( x = pred))

ok
```


```{r}
any(p5$pred < 0)
```
```{r}
  # generate raw performance metrics 
  raw_performance_measures <- 
    p5 %>% 
    mutate(iter  = as.factor(iter), 
           class = as.factor(class)) %>% 
    group_by(iter) %>%
    group_modify(~performance_statistics(pred = .x$pred, class = .x$class))
raw_performance_measures
```

```{r}
p6
```
```{r}
p6 %>% 
  filter(is.na(pred == TRUE))

sum(is.na(p6$pred))
```
```{r}
r6 %>%
  filter(problem != 0)
```

```{r}
r6 %>% 
  filter(iter == 79)
```

```{r}
sc = 3
p = 6
i = 79
input <- set[[sc]]

sc_ef <- input$event_frac
pO    <- 100/sc_ef * (1-sc_ef)


    # set seed
    seed <- pull(seed.farm[sc])[i]
    seed
    set.seed(seed)
    
    # train and test data
    df <- generate_data(input)
    tf <- generate_data(input, test = TRUE)
    ef <- mean(as.numeric(df$outcome)-1)

```

```{r}
df
```

```{r}
do_eas(df, tf, i)
```

```{r}

df <- df 
test <- tf
  a <- tryCatch.W.E(
    expr    = { 
      train_x <- df %>% dplyr::select(-outcome)
      train_y <- df %>% dplyr::pull(outcome)
      test_x  <- test %>% dplyr::select(-outcome)
      
      mod  <- EasyEnsemble(train_x, train_y)
      pred <- predict(mod, test_x, type = "probability")$X1
    }
  )
```

```{r}
out = p6
  # generate raw performance metrics
  raw_performance_measures <-
    out %>%
    mutate(iter  = as.factor(iter),
           class = as.factor(class)) %>%
    group_by(iter) %>%
    group_modify(~performance_statistics(pred = .x$pred, class = .x$class))

```

```{r}
raw_performance_measures %>% 
  filter(iter %in% c(14, 20, 79))
```

```{r}
r6
```
```{r}
source("functions.R")
```

```{r}
get_stats <- function(dataframe){
    dataframe %>%
    mutate(iter  = as.factor(iter),
           class = as.factor(class)) %>%
    group_by(iter) %>%
    group_modify(~performance_statistics(pred = .x$pred, class = .x$class))
}
```


```{r}
performance_statistics <- function(pred, class){
  if(any(is.na(pred)) == FALSE & any(pred < 0) == TRUE){
    pred[pred < 0 ] <- 1e-16
  }
  
  return(
    tibble(
      var = var(pred),
      auc = auroc(pred, class),
      bri = scaled_brier_score(pred, class), 
      int = calibration_intercept(pred, class), 
      slp = calibration_slope(pred, class)
      )
    )
}
```

```{r}
var(pred)
```

