---
title: "results"
output: pdf_document
---

# Set Up 
```{r}
library(tidyverse)
library(ggridges)
```

```{r}
a <- list.files(path = "./sim_results/per_iter_results/", pattern = ".rds") %>%
  paste0("./sim_results/per_iter_results/", .) %>%
  map(readRDS) %>% 
  bind_rows()
```

```{r}
b <- list.files(path = "./sim_results/predictions/", pattern = ".rds") %>%
  paste0("./sim_results/predictions/", .) %>%
  map(readRDS) %>% 
  bind_rows()
```

------------------------ empirical metrics  --------------------------------------

## Scenario 1 
```{r}
sc1 <- a %>% filter(scenario == 1)
```

```{r}
sc1 %>% 
  mutate(iter = as.factor(iter), 
         pair_id = as.factor(pair_id), 
         scenario = as.numeric(scenario), 
         problem = as.numeric(problem), 
         sc_ef = as.numeric(sc_ef), 
         obs_ef = as.numeric(obs_ef), 
         new_ef = as.numeric(obs_ef)
         ) %>% 
  filter (problem == 1 | var == 0)
```

```{r}
sc1[!complete.cases(sc1), ]
```

```{r}
sc1 %>% 
  group_by(pair_id) %>% 
  mutate(scenario = as.numeric(scenario)) %>% 
  summarise(
    scenario = mean(scenario),
    auc_mean = mean(auc, na.rm = T), 
    auc_sd   = sd  (auc, na.rm = T), 
    bri_mean = mean(bri, na.rm = T), 
    bri_sd   = sd  (bri, na.rm = T), 
    int_mean = mean(int, na.rm = T), 
    int_sd   = sd  (int, na.rm = T),
    slp_mean = mean(slp, na.rm = T), 
    slp_sd   = sd  (slp, na.rm = T)
    ) %>% 
  relocate(scenario)
```

## Scenario 2 

```{r}
sc2 <- a %>% filter(scenario == 2)
```

```{r}
sc2 %>% 
  mutate(iter = as.factor(iter), 
         pair_id = as.factor(pair_id), 
         scenario = as.numeric(scenario), 
         problem = as.numeric(problem), 
         sc_ef = as.numeric(sc_ef), 
         obs_ef = as.numeric(obs_ef), 
         new_ef = as.numeric(obs_ef)
         ) %>% 
  filter (problem == 1 | var == 0)
```

```{r}
sc2[!complete.cases(sc2), ]
```




--------------------------- calibration plots --------------------------------------------------------------------------------------------------


```{r}
b %>% 
  filter(scenario == 1) %>%
  filter(pair_id == 30) %>% 
  calibration_plot()
```
```{r}
sc1_plot <- 
  b %>% 
  filter(scenario == 1) %>% 
    merge(pairs, id = pair_id) %>% 
    filter(problematic != 1) %>% 
    drop_na() %>% 
    ggplot(aes(x = pred, y = class, group = as.factor(iter))) +
    geom_line(stat = "smooth",
              method = stats::loess, 
              formula = y ~ x,
              se = F, 
              linewidth = 0.5, 
              alpha = 0.1, 
              aes(color = as.factor(algorithms))) +
    geom_abline(slope = 1, intercept = 0, size = 1) +
    theme_minimal() +
    xlab(" ") + 
    ylab(" ") +
    xlim(0,1) + 
    ylim(0,1) + 
    facet_grid(algorithms ~ corrections) +
    theme(legend.position = "none")   
```

```{r}
sc2_plot <- 
  b %>% 
  filter(scenario == 2) %>% 
  merge(pairs, id = pair_id) %>% 
    filter(problematic != 1) %>% 
    drop_na() %>% 
    ggplot(aes(x = pred, y = class, group = as.factor(iter))) +
    geom_line(stat = "smooth",
              method = stats::loess, 
              formula = y ~ x,
              se = F, 
              linewidth = 0.5, 
              alpha = 0.1, 
              aes(color = as.factor(algorithms))) +
    geom_abline(slope = 1, intercept = 0, size = 1) +
    theme_minimal() +
    xlab(" ") + 
    ylab(" ") +
    xlim(0,1) + 
    ylim(0,1) + 
    facet_grid(algorithms ~ corrections) + 
    theme(legend.position = "none")
```

```{r, fig.height = 7, fig.width = 7}
sc1_plot 
```


```{r,fig.height = 7, fig.width = 7}
sc2_plot
```















