---
title: "Imbalance Corrections"
output: html_document
---

# Set Up: 
```{r}
# functions
source("functions.R")

# settings
set <- readRDS("data-generating-mechanism/set.RData")
sc <- set[[3]]
```

# 1. None 
```{r}
# generate data 
df <- generate_data(sc)
df
```


# 2. RUS 
```{r}
library(ROSE)

# over-sample
df.rus <- ROSE::ovun.sample(outcome~., data = df, method = "under")$data

# check balance
table(df.rus$outcome)

# nobs 
nrow(df.rus)
```

```{r}
# function
rus <- function(df){
  # conducts random under-sampling technique to correct for class imbalance 
  # input:  data frame
  # output: data frame (class balanced)
  
  df.rus <- ROSE::ovun.sample(outcome~., data = df, method = "under")$data
  return(df.rus)
}

rus(df)  # returns data frame with $outcome as class
```

# 3. ROS 
```{r}
library(ROSE)

# over-sample
df.ros <- ROSE::ovun.sample(outcome~., data = df, method = "over")$data

# check balance
table(df.ros$outcome)

# nobs 
nrow(df.ros)
```

```{r}
# function
ros <- function(df){
  # conducts random over-sampling technique to correct for class imbalance 
  # input:  data frame
  # output: data frame (class balanced)
  
  df.rus <- ROSE::ovun.sample(outcome~., data = df, method = "over")$data
  return(df.rus)
}


ros(df)  # returns data frame with $outcome as class
```

# 4. SMOTE 
```{r}
## DECISION: pick k, number of nearest neigbors for SMOTE 

library(smotefamily)

# smote 
df.smote <- smotefamily::SMOTE(df[-1], target = df[1], K = 5)$data

# check balance 
table(df.smote$class)
```

```{r}
smote <- function(df, K = 5){
  # conducts SMOTE to correct for class imbalance 
  # input:  data frame
  #         class must be first column in data frame
  #
  # output: class-balanced data frame 
  
  df.smote <- smotefamily::SMOTE(df[-1], target = df[1], K)$data
    
  df.smote <- 
    df.smote %>% 
      rename("outcome" = "class") %>% 
      relocate(outcome) %>% 
      mutate(outcome = as.factor(outcome))
  
  return(df.smote)
}

smote(df) # returns data frame with $outcome as class
```


# 5. SMOTE-ENN 
```{r}
# DECISION: pick k1 and k2, nn for SMOTE and ENN, respectively

# IRIC package 
source("IRIC-master/R/Data level/SmoteENN.R")
library(RANN)

# smote-enn 
df.smote.enn <- SmoteENN(x = df[-1], y = df[1], k1 = 5, k2 = 3)

# check balance
table(df.smote.enn$outcome)

# nobs
nrow(df.smote.enn)
```

```{r}
smoteenn <- function(df){
  # conducts SMOTE-ENN to correct for class imbalance 
  # input:  data frame
  #         class must be first column in data frame
  #
  # output: class balanced data frame
  
  
  df.smote.enn <- SmoteENN(x = df[-1], y = df[1])
  df.smote.enn <- 
    df.smote.enn %>% 
      relocate("outcome")
      
  return(df.smote.enn)
}

smoteenn(df) # returns data frame with $outcome as class
```


```{r}
x <- smoteenn(df)

table(df$outcome)

table(x$outcome)
```




