---
title: "simulation study"
output: html_document
---

```{r}
# set up

# general
library(tidyverse)
library(MASS)
library(caret)
library(pROC)

# functions
source("functions.R")

# seeds 
seed.farm <- readRDS("seeds/seedfarm.RData")

# simulation scenarios 
set <- readRDS("data-generating-mechanism/set.RData")
```

```{r}
# manual package installation

# ROSE 
source("packages/ROSE-master/R/data_balancing_funcs.R")
source("packages/ROSE-master/R/estimation_funcs.R")
source("packages/ROSE-master/R/ROSE_eval.R")

# IRIC 
library(RANN)
library(foreach)
source("packages/IRIC-master/R/Ensemble-based level/EasyEnsemble.R")
source("packages/IRIC-master/R/Data level/SmoteENN.R")
source("packages/IRIC-master/R/Data level/SMOTE.R")

# ebmc 
source("packages/ebmc-master/R/ebmc.R")

# simsalapar
source("packages/simsalapar-master/R/tryCatchWE.R")
```

```{r}
# simulation code 

sim_in_parallel <- function(scenario, pair, start, stop){
  
  # set up 
  sc    = scenario
  p     = pair
  start = start
  stop  = stop
  out   = c()
  info  = c()
  
  # save scenario input and correction/algorithm pair 
  input      <- set[[sc]]
  pair_id    <- as.character(pairs[p,1])
  correction <- as.character(pairs[p,2])
  algorithm  <- as.character(pairs[p,3])
  
  # simulation
  for (i in start:stop){
    
    # set seed
    seed <- pull(seed.farm[sc])[i]
    set.seed(seed)
    
    # train and test data
    df <- generate_data(input)
    tf <- generate_data(input, test = TRUE)
    ef <- mean(as.numeric(df$outcome)-1)
    percO <- 100/ef * (1-ef)
    
    # pre-process step 
    if(correction == "rus"){ df <- do_rus(df) }
    if(correction == "ros"){ df <- do_ros(df) }
    if(correction == "smo"){ df <- do_smo(df, percO) }
    if(correction == "sen"){ df <- do_sen(df, percO) }

    # implement algorithm 
    if(algorithm == "logistic_regression")   { o <- do_lrg(df, tf, i) }
    if(algorithm == "support_vector_machine"){ o <- do_svm(df, tf, i) }
    if(algorithm == "random_forest")         { o <- do_rnf(df, tf, i) }
    if(algorithm == "xgboost")               { o <- do_xgb(df, tf, i) }
    if(algorithm == "rusboost")              { o <- do_rub(df, tf, i) }
    if(algorithm == "easy_ensemble")         { o <- do_eas(df, tf, i) }
    
    # save iteration information
    iter_info <- 
      cbind("scenario" = sc,
            "pair_id"  = p,
            "iter"     = i,
            "seed"     = seed, 
            "problem"  = o$problem,
            "warning"  = as.character(o$warning), 
            "err"      = as.character(o$error), 
            "sc_ef"    = input$event_frac,
            "obs_ef"   = round(ef, 3),
            "new_ef"   = round(mean(as.numeric(df$outcome)-1), 3)
            )
    
    # store results
    out  <- rbind(out, o$pred)      # predictions
    info <- rbind(info, iter_info)  # iteration info
  }
  
  # save predicted probabilities
  out  <- cbind("scenario" = sc, "pair_id" = p, out)
  out  <- as.data.frame(out)  %>% `rownames<-`( NULL )
  saveRDS(out, file = paste0("sim_results/predictions/sc", sc, "_p", pair_id, "_", start, "_", stop,".rds"))
  
  # save iteration info 
  info <- as.data.frame(info) %>% `rownames<-`( NULL )
  saveRDS(info, file = paste0("sim_results/iteration_info/sc", sc, "_p", pair_id, "_", start, "_", stop, ".rds"))
  
  # save per iteration results
  results <- get_stats(out) 
  results <- merge(info, results, by = "iter")
  saveRDS(results, paste0("sim_results/per_iter_results/sc", sc, "_p", pair_id, "_", start, "_", stop,".rds"))
  
  #return(list(out, info, results))
}
```
 
```{r}
for(i in 1:30){
  
w = 1   # sc
x = i   # p
y = 1   # start
z = 2 # stop

sim_in_parallel(scenario = w, pair = x, start = y, stop = z)
print(x)
}
```

```{r}
sc = 2
pair_id = 
start = 1
stop = 100

a <- readRDS(paste0("sim_results/predictions/sc", sc, "_p", pair_id, "_", start, "_", stop,".rds"))
b <- readRDS(paste0("sim_results/per_iter_results/sc", sc, "_p", pair_id, "_", start, "_", stop,".rds"))
c <- readRDS(paste0("sim_results/iteration_info/sc", sc, "_p", pair_id, "_", start, "_", stop, ".rds"))
```

```{r}
a
b
c
```

```{r}
calibration_plot(a)
```



```{r}
library(ggridges)

n <- sample(100, 10)

a %>% 
  mutate(iter = as.factor(iter)) %>% 
  filter(iter %in% n) %>% 
  ggplot(aes(x = pred, y = iter)) + 
  geom_density_ridges(fill = "aliceblue", scale = 0.5)+
  theme_minimal()
```

-------------------------- one iteration ------------------------------------------------------------

```{r}
source("functions.r")
```

```{r}
calibration_plot(out)
```


------------------------- catch errors in the algorithms --------------------------------------------

```{r}
source("functions.R")
```

```{r}
w = 3   # sc
x = 15   # p
y = 1   # start
z = 100 # stop

a <- sim_in_parallel(scenario = w, pair = x, start = y, stop = z)
```


```{r}
mean(a[[3]]$auc)
mean(a[[3]]$bri)
mean(a[[3]]$int)
mean(a[[3]]$slp)
```
```{r}
a
```
```{r}
min(a[[1]]$pred)
```

```{r}
calibration_plot(a[[1]])
```

```{r}
library(ggridges)
n <- sample(100, 10)

a[[1]]%>% 
  mutate(iter = as.factor(iter)) %>% 
  filter(iter %in% n) %>% 
  ggplot(aes(x = pred, y = iter)) + 
  geom_density_ridges(fill = "aliceblue", scale = 0.5)+
  theme_minimal()
```

------------------------- check each pre-process technique ------------------------------------------- 



```{r}
  # set up 
  sc    = 25
  p     = 7
  out   = c()
  info  = c()
  
  # save scenario input and correction/algorithm pair 
  input      <- set[[sc]]
  pair_id    <- as.character(pairs[p,1])
  correction <- as.character(pairs[p,2])
  algorithm  <- as.character(pairs[p,3])
  
  # simulation
for(i in 1:2000){
    
    # set seed
    seed <- pull(seed.farm[sc])[i]
    set.seed(seed)
    
    # train and test data
    df <- generate_data(input)
    print(i)
    a <- do_rus(df)
    b <- do_ros(df)
}
```

```{r}
table(df$outcome)
```
```{r}
formula <- outcome~.
data    <- df

df.rus <-  ROSE::ovun.sample(formula, data, method = "under")$data
```

