---
title: "sim"
author: "Alex Carriero"
output: 
   bookdown::html_document2:
    toc: true
    toc_depth: 3
    toc_float: true
    number_sections: false
    theme: paper
---
# Set up 
```{r, warning = F, message = F, echo = F}
# libraries 

# general
library(tidyverse)
library(devtools)
library(MASS)

# pre-processing corrections
library(ROSE)
library(smotefamily)

# models 
library(caret)
library(e1071)
library(ranger)
library(xgboost)
library(ebmc)

# simulation features 
library(pROC)
library(SimDesign)
library(simsalapar)

# IRIC package
source("IRIC-master/R/Ensemble-based level/EasyEnsemble.R")
source("IRIC-master/R/Data level/SmoteENN.R")
library(RANN)

# plots
library(patchwork)
library(gridExtra)
library(ggridges)
```

```{r}
# functions
source("functions.R")

# simulation scenarios 
set <- readRDS("data-generating-mechanism/set.RData")
```
 
```{r}
# new functions and things 
# correction - algorithm combinations 

algorithms   <- c("logistic_regression", "support_vector_machine", "random_forest", "xgboost", "rusboost", "easy_ensemble")
corrections  <- c("control", "rus", "ros", "smo", "sen")

pairs <- 
  expand_grid(corrections, algorithms) %>% 
  mutate(pair_id = c(1:30)) %>% 
  relocate(pair_id)

pairs
```

```{r}
# generating all the data function
generate_all_the_data <- function(sc, iter){
  
  scenario      <- set[[sc]]
  storage_data  <- vector(mode = "list", length = iter)
  storage_test  <- vector(mode = "list", length = iter)
  
  for (i in 1:iter){
    storage_data[[i]] <- generate_data(scenario)
    storage_test[[i]] <- generate_data(scenario, test = TRUE)
  }

  out <- list("data" = storage_data, "test" = storage_test)
  saveRDS(out, file = paste0("generated_data/scenario_", sc,".rds"))
}

# generate_all_the_data(sc = 2, iter = 2000)
```



# Sim in Parallel 
```{r}
sim_in_parallel <- function(scenario, pair, start, stop){
  
  # set up 
  sc    = scenario
  start = start
  stop  = stop
  out   =  c()
  
  # save correction/algorithm pair 
  pair_id    <- as.character(pair[,1])
  correction <- as.character(pair[,2])
  algorithm  <- as.character(pair[,3])
  
  
  # load data for scenario 
  all_the_data <- readRDS(paste0("generated_data/scenario_", sc,".rds"))
  data <- all_the_data$data
  test <- all_the_data$test
  
  
  # pre-process step 
  if(correction == "rus"){ data <- lapply(data, do_rus) }
  if(correction == "ros"){ data <- lapply(data, do_ros) }
  if(correction == "smo"){ data <- lapply(data, do_smote) }
  if(correction == "sen"){ data <- lapply(data, do_smoteenn) }
  
  
  # implement algorithm
  if(algorithm == "logistic_regression"){
    for(i in start:stop){
      pred  <- do_lrg(data[[i]], test[[i]], i)
      out   <- rbind(out, pred)
    }
  }
  
  if(algorithm == "support_vector_machine"){
    for(i in start:stop){
      pred <- do_svm(data[[i]], test[[i]], i)
      out  <- rbind(out, pred)
    }
  }
  
  if(algorithm == "random_forest"){
    for(i in start:stop){
      pred <- do_rnf(data[[i]], test[[i]], i)
      out  <- rbind(out, pred)
    }
  }
  
  if(algorithm == "xgboost"){
    for(i in start:stop){
      pred <- do_xgb(data[[i]], test[[i]], i)
      out  <- rbind(out, pred)
    }
  }
  
  if(algorithm == "rusboost"){
    for(i in start:stop){
      pred <- do_rub(data[[i]], test[[i]], i)
      out  <- rbind(out, pred)
    }
  }
  
  if(algorithm == "easy_ensemble"){
    for(i in start:stop){
      pred <- do_ees(data[[i]], test[[i]], i)
      out  <- rbind(out, pred)
    }
  }
  
  out <- as.data.frame(out) %>% `rownames<-`( NULL )
  
  
  # save predicted probabilities 
  saveRDS(out, file = paste0("sim_results/predictions/sc", sc, "_p", pair_id, "_", start, "_", stop,".rds"))
  
  
  # save raw performance metrics 
  raw_performance_measures <- 
    out %>% 
    mutate(iter  = as.factor(iter), 
           class = as.factor(class)) %>% 
    group_by(iter) %>%
    group_modify(~performance_statistics(pred = .x$pred, class = .x$class, converge = .x$convergence))
      
  saveRDS(raw_performance_measures, paste0("sim_results/raw_performance_metrics/sc", sc, "_p", pair_id, "_", start, "_", stop,".rds"))
  
  
}
```


```{r}
sim_in_parallel(3, pairs[8,], start = 1, stop = 2000) 
```


------ single iteration code --------------------------------------------------

```{r}
sc = 1
all_the_data <- readRDS(paste0("generated_data/scenario_", sc,".rds"))
data <- all_the_data$data
test <- all_the_data$test
```

```{r}
pair       = pairs[7,]
pair_id    = as.character(pair[,1])
correction = as.character(pair[,2])
algorithm  = as.character(pair[,3])

if(correction == "rus"){ data <- lapply(data, do_rus) }
```

```{r}
table(data[[1]]$outcome)
```

```{r}
start = 1
stop  = 20
out <- c()

for(i in start:stop){
  pred  <- lrg(data[[i]], test[[i]])
  pred  <- cbind(pred, "iter" = i, "class" = as.numeric(test[[i]]$outcome) - 1)
  out   <- rbind(out, pred)
}
```

```{r}
out <- as.data.frame(out) %>% `rownames<-`( NULL )

out
saveRDS(out, file = paste0("sim_results/predictions/sc", sc, "_", start, "_", stop,".rds"))
```

```{r}
raw_performance_measures <- 
    out %>% 
    mutate(iter  = as.factor(iter), 
          class = as.factor(class)) %>% 
    group_by(iter) %>%
    group_modify(~performance_statistics(pred = .x$pred, class = .x$class))
  
saveRDS(out, paste0("sim_results/raw_performance_metrics/sc", sc, "_", start, "_", stop,".rds"))
```


------------------ investigate weird results -----------------------------------


------------------ support vector machine code ---------------------------------

```{r}
# notes: 

# need to control randomness -- seeds
# is it worth saving C every iteration
```

```{r}
all_data <- readRDS("generated_data/scenario_3.rds")
```

```{r}
data <- all_data$data
test <- all_data$test
```

```{r}
set.seed(40)
data <- lapply(data, do_rus)
```

```{r}
data[[2]]
```

```{r}
# caret
library(caret)
```


```{r}
deviance <- function(data, lev = NULL, model = NULL) {
  obs  <- as.numeric(data$obs) - 1
  pred <- data$one
  
  pred[pred == 0] <- 1e-16
  pred[pred == 1] <- 1-1e-16
  
  dev <- -2*sum(obs*log(pred) + (1-obs)*log(1-pred))
  
  c(Deviance = dev)
}
```

```{r}
do_svm <- function(df, test, iter){
  
  # ensure correct factor levels, and character labels 
  df$outcome     = factor(df$outcome, levels=c(0,1), ordered = TRUE)
  levels(df$outcome) <- c("zero", "one")
  
  # model 
  train_ctrl <- trainControl(method = "cv", number = 5, summaryFunction = deviance, classProbs = T)
  mod        <- train(outcome ~., 
                      data = df, 
                      method = "svmLinear", 
                      metric = "Deviance",
                      maximize = FALSE, 
                      trControl = train_ctrl,  
                      )
  
  pred <- predict(mod, newdata = test, type = "prob")["one"]
  colnames(pred) = NULL
  
  # store results
  pred <- cbind("pred" = pred, "iter" = iter, "class" = as.numeric(test$outcome) - 1, "convergence" = 0)
  return(pred)
}
```


```{r}
# NEED A GENERAL P 

tunegrid <- expand.grid(
    mtry = 1:8,
    min.node.size = 1:10,
    splitrule = "gini"
)


do_rnf <- function(df, test, iter){
  
  # ensure correct factor levels, and character labels 
  df$outcome     = factor(df$outcome, levels=c(0,1), ordered = TRUE)
  levels(df$outcome) <- c("zero", "one")
  
  # model 
  train_ctrl <- trainControl(method = "cv", number = 5, summaryFunction = deviance, classProbs = T)
  mod        <- train(outcome ~., 
                      data = df, 
                      method = "ranger", 
                      metric = "Deviance",
                      maximize = FALSE, 
                      trControl = train_ctrl,  
                      tuneGrid = tunegrid
                      )
  
  pred <- predict(mod, newdata = test, type = "prob")["one"]
  colnames(pred) = NULL
  
  # store results
  pred <- cbind("pred" = pred, "iter" = iter, "class" = as.numeric(test$outcome) - 1, "convergence" = 0)
  return(pred)
}
```

```{r}
do_xgb <- function(df, test, iter){
  
  # ensure correct factor levels, and character labels 
  df$outcome     = factor(df$outcome, levels=c(0,1), ordered = TRUE)
  levels(df$outcome) <- c("zero", "one")
  
  # model 
  train_ctrl <- trainControl(method = "cv", number = 5, summaryFunction = deviance, classProbs = T)
  mod        <- train(outcome ~., 
                      data = df, 
                      method = "xgbTree", 
                      metric = "Deviance",
                      maximize = FALSE, 
                      trControl = train_ctrl, 
                      verbosity = 0, 
                      verbose = FALSE
                      )
  
  pred <- predict(mod, newdata = test, type = "prob")["one"]
  colnames(pred) = NULL
  
  # store results
  pred <- cbind("pred" = pred, "iter" = iter, "class" = as.numeric(test$outcome) - 1, "convergence" = 0)
  return(pred)
}
```

```{r}
i = 1
out <- do_svm(data[[i]], test[[i]], i)
out <- as.data.frame(out) %>% `rownames<-`( NULL )
out
```

```{r}
out <- do_rnf(data[[i]], test[[i]], i)
out <- as.data.frame(out) %>% `rownames<-`( NULL )
out
```

```{r}
out <- do_xgb(data[[i]], test[[i]], i)
out <- as.data.frame(out) %>% `rownames<-`( NULL )
out
```

```{r}
raw_performance_measures <- 
    out %>% 
    mutate(iter  = as.factor(iter), 
           class = as.factor(class)) %>% 
    group_by(iter) %>%
    group_modify(~performance_statistics(pred = .x$pred, class = .x$class, converge = .x$convergence))

raw_performance_measures
```

```{r}
# RUB NOTES: 


# 1 is supposed to denote minority 
# 0 is supposed to denote majority -- probelmatic potentially for balanced case --- not great 

# algorithm decision: C5.0 Decision Tree 
# size -- TBD 

## see how sensitive results are to changes in size 
```


