---
title: "Results"
output: html_document
---

# set up
```{r, warning = F, message = F}
library(tidyverse)
library(patchwork)
library(pROC)
library(simsalapar)
library(stats)

source("./../masters_thesis/simulation_series/functions.R")
source("process_results.R")
```


# add brier score 
```{r}
# in our simulation study, scaled brier score was computed. 
# this metric has proven to be difficult to interpret in the presence of extreme class imbalance (producing large negative numbers)
# there is also discrepancy in the literature about how it is defined. 

# for this reason, we also compute brier score. 

save_brier_scores("sc18")
```

# retrieve summaries 

```{r}
1:17 %>% 
  paste0("sc", .) %>%
  map(function(x) get_summary(x)) # make the summary function save the summary
```

```{r}
sc1 <- get_summary("sc1")
saveRDS(sc1, "./../masters_thesis/visualize_results/results/results_sc1_new.RData")

sc2 <- get_summary("sc2")
saveRDS(sc2, "./../masters_thesis/visualize_results/results/results_sc2_new.RData")

sc3 <- get_summary("sc3")
saveRDS(sc3, "./../masters_thesis/visualize_results/results/results_sc3_new.RData")

sc4 <- get_summary("sc4")
saveRDS(sc4, "./../masters_thesis/visualize_results/results/results_sc4_new.RData")

sc5 <- get_summary("sc5")
saveRDS(sc5, "./../masters_thesis/visualize_results/results/results_sc5_new.RData")

sc6 <- get_summary("sc6")
saveRDS(sc6, "./../masters_thesis/visualize_results/results/results_sc6_new.RData")

sc7 <- get_summary("sc7")
saveRDS(sc7, "./../masters_thesis/visualize_results/results/results_sc7_new.RData")

sc8 <- get_summary("sc8")
saveRDS(sc8, "./../masters_thesis/visualize_results/results/results_sc8_new.RData")

sc9 <- get_summary("sc9")
saveRDS(sc9, "./../masters_thesis/visualize_results/results/results_sc9_new.RData")

sc10 <- get_summary("sc10")
saveRDS(sc10, "./../masters_thesis/visualize_results/results/results_sc10_new.RData")

sc11 <- get_summary("sc11")
saveRDS(sc11, "./../masters_thesis/visualize_results/results/results_sc11_new.RData")

sc12 <- get_summary("sc12")
saveRDS(sc12, "./../masters_thesis/visualize_results/results/results_sc12_new.RData")

sc13 <- get_summary("sc13")
saveRDS(sc13, "./../masters_thesis/visualize_results/results/results_sc13_new.RData")

sc14 <- get_summary("sc14")
saveRDS(sc14, "./../masters_thesis/visualize_results/results/results_sc14_new.RData")

sc15 <- get_summary("sc15")
saveRDS(sc15, "./../masters_thesis/visualize_results/results/results_sc15_new.RData")

sc16 <- get_summary("sc16")
saveRDS(sc16, "./../masters_thesis/visualize_results/results/results_sc16_new.RData")

sc17 <- get_summary("sc17")
saveRDS(sc17, "./../masters_thesis/visualize_results/results/results_sc17_new.RData")

sc18 <- get_summary("sc18")
saveRDS(sc18, "./../masters_thesis/visualize_results/results/results_sc18_new.RData")
```


# calibration plots 

```{r, warning = F, message = F, fig.height = 14, fig.width = 14}
# save coordinates
sc17<- 
  1324:2000%>% 
  map(function(x) save_plot_coords(x, "sc17"))
```

```{r}
# generate calibration plots
  scN <- paste0("sc", 9)
  
  df <- 
    list.files(path = paste0("./processed_results/plot_coords/raw_results/", scN, "/"), pattern = ".rds") %>%
    paste0("./processed_results/plot_coords/raw_results/", scN, "/", .) %>%
    map(readRDS) %>% 
    bind_rows() %>% 
    as.data.frame() %>% 
    drop_na() %>%
    pre_plot()

  p <- plot_from_coords(df)

  ggsave(paste0("./../masters_thesis/visualize_results/results/calibration_plot_", scN, ".png"), 
         plot = p,  width = 14, height = 14)

``` 

# re-calibrate

```{r}
# recalibrate raw results 

sc12 <-
  8:2000 %>%
  map(function(x) recalibrate_everything(x, "sc12"))
```

```{r}
sc17 <-
  1270:2000 %>%
  map(function(x) recalibrate_everything(x, "sc17"))
```

# re-calibrated summaries 

```{r}
sc1 <- get_summary("sc1", recalibrated = T)
saveRDS(sc1, "./../masters_thesis/visualize_results/results/results_sc1_recalibrated.RData")

sc2 <- get_summary("sc2", recalibrated = T)
saveRDS(sc2, "./../masters_thesis/visualize_results/results/results_sc2_recalibrated.RData")

sc3 <- get_summary("sc3", recalibrated = T)
saveRDS(sc3, "./../masters_thesis/visualize_results/results/results_sc3_recalibrated.RData")

sc4 <- get_summary("sc4", recalibrated = T)
saveRDS(sc4, "./../masters_thesis/visualize_results/results/results_sc4_recalibrated.RData")

sc5 <- get_summary("sc5", recalibrated = T)
saveRDS(sc5, "./../masters_thesis/visualize_results/results/results_sc5_recalibrated.RData")

sc6 <- get_summary("sc6", recalibrated = T)
saveRDS(sc6, "./../masters_thesis/visualize_results/results/results_sc6_recalibrated.RData")

sc7 <- get_summary("sc7", recalibrated = T)
saveRDS(sc7, "./../masters_thesis/visualize_results/results/results_sc7_recalibrated.RData")

sc8 <- get_summary("sc8", recalibrated = T)
saveRDS(sc8, "./../masters_thesis/visualize_results/results/results_sc8_recalibrated.RData")

sc9 <- get_summary("sc9", recalibrated = T)
saveRDS(sc9, "./../masters_thesis/visualize_results/results/results_sc9_recalibrated.RData")

sc10 <- get_summary("sc10", recalibrated = T)
saveRDS(sc10, "./../masters_thesis/visualize_results/results/results_sc10_recalibrated.RData")

sc11 <- get_summary("sc11", recalibrated = T)
saveRDS(sc11, "./../masters_thesis/visualize_results/results/results_sc11_recalibrated.RData")

sc13 <- get_summary("sc13", recalibrated = T)
saveRDS(sc13, "./../masters_thesis/visualize_results/results/results_sc13_recalibrated.RData")

sc14 <- get_summary("sc14", recalibrated = T)
saveRDS(sc14, "./../masters_thesis/visualize_results/results/results_sc14_recalibrated.RData")

sc16 <- get_summary("sc16", recalibrated = T)
saveRDS(sc16, "./../masters_thesis/visualize_results/results/results_sc16_recalibrated.RData")
```

```{r}
sc12 <- get_summary("sc12", recalibrated = T)
saveRDS(sc12, "./../masters_thesis/visualize_results/results/results_sc12_recalibrated.RData")

sc15 <- get_summary("sc15", recalibrated = T)
saveRDS(sc15, "./../masters_thesis/visualize_results/results/results_sc15_recalibrated.RData")

sc17 <- get_summary("sc17", recalibrated = T)
saveRDS(sc17, "./../masters_thesis/visualize_results/results/results_sc17_recalibrated.RData")
```


# re-calibrated calibration plots 

```{r, warning = F, message = F, fig.height = 14, fig.width = 14}
# generate plot coordinates 

for (j in 16:16){
  
  scN <- paste0("sc", j)
  
  # 1:2000 %>%
  # map(function(x) recalibrate_everything(x, scN))
  
  1:2000 %>% 
  map(function(x) save_plot_coords(x, scN, recalibrated = TRUE))
  
}

# generate calibration plots
for(i in 16:16){
  
  scN <- paste0("sc", i)

  df <- 
    list.files(path = paste0("./processed_results/plot_coords/recalibrated_results/", scN, "/"), pattern = ".rds") %>%
    paste0("./processed_results/plot_coords/recalibrated_results/", scN, "/", .) %>%
    map(readRDS) %>% 
    bind_rows() %>% 
    as.data.frame() %>%
    drop_na() %>%
    pre_plot()

  p <- plot_from_coords(df)

  ggsave(paste0("./../masters_thesis/visualize_results/results/calibration_plot_", scN, "_recalibrated.png"), 
        plot = p,  width = 14, height = 14)
}
``` 




# manuscript figures

```{r}
# calibration plots 
for(i in 4:6){
  
  scN <- paste0("sc", i)

  df <- 
    list.files(path = paste0("./processed_results/plot_coords/raw_results/", scN, "/"), pattern = ".rds") %>%
    paste0("./processed_results/plot_coords/raw_results/", scN, "/", .) %>%
    map(readRDS) %>% 
    bind_rows() %>% 
    as.data.frame() %>% 
    drop_na() %>%
    pre_plot()

  p <- plot_from_coords(df)

  ggsave(paste0("./../masters_thesis/thesis_manuscript/results/calibration_plot_manuscript_", scN, ".png"), plot = p,  width = 12, height = 15)
}
```

```{r}
# performance metric plots 

for(i in 4:6){
  
  scN <- paste0("sc", i)

  df <- readRDS(paste0("./../masters_thesis/visualize_results/results/results_", scN, "_new.RData"))
  df <- df$overall_dataframe
  
  a <- pm_plot(df, method = "auc", 0.6, 1)

  b <- pm_plot(df, method = "bri", 0, 0.35)

  c <- pm_plot(df, method = "int", -6, 2)

  d <- pm_plot(df, method = "slp", -0.5, 5)

  P <- a + b + c + d + plot_layout(ncol = 1)

  ggsave(paste0("./../masters_thesis/thesis_manuscript/results/performance_metrics_manuscript_", scN, ".png"), plot = P,  width = 12, height = 15)

}
```


# manuscript tables

```{r}
# make tables to display errors 

make_table_algorithm("logistic_regression")
make_table_algorithm("support_vector_machine")
make_table_algorithm("random_forest")
make_table_algorithm("xgboost")
make_table_algorithm("rusboost")
make_table_algorithm("easy_ensemble")

make_table_corrections()
```



# troubles

## not everything ran on hpc
```{r}
# example code 

test_again <- sc18$overall_dataframe %>% 
  mutate(iter = as.numeric(iter)) 

a <- unique(test_again$iter)
b <- as.numeric(c(1:400))

to_do <- setdiff(b,a)
to_do

saveRDS(to_do, file = "to_do_sc18.rds")
```

## out of storage ? 
```{r}
Cstack_info()
```

## old code  
```{r}
#any_na_row <- df[!complete.cases(df), ]
```


## separation in results 
```{r}
df <- 
  sc1$overall_dataframe 


df <- 
  df %>%
  mutate(obs_ef = as.numeric(obs_ef)) %>% 
  mutate(chance_imbalance = cut(obs_ef, breaks = c(0, 0.5, 1), labels = c("<0.5", ">0.5"))) %>% 
  select(scenario, pair_id, iter, chance_imbalance)

df
```
```{r}
scN <- "sc1"
coords <- 
    list.files(path = paste0("./processed_results/plot_coords/raw_results/", scN, "/"), pattern = ".rds") %>%
    paste0("./processed_results/plot_coords/raw_results/", scN, "/", .) %>%
    map(readRDS) %>% 
    bind_rows() %>% 
    as.data.frame() %>% 
    drop_na() %>%
    pre_plot()

color_df<- 
  df %>% 
  mutate(iter = as.numeric(iter)) %>% 
  merge(coords, by= c("pair_id", "iter"))

p <- plot_from_coords(color_df) 
```

```{r, fig.height = 8, fig.width = 8}
p
```





